version: "3.7"

volumes:
        jenkins-home:
        mongo:

services:
        ui:
                image: hmsbennett/pool_ui:latest
                ports:
                        - target: 80
                          published: 80
                depends_on:
                        - jenkins
                        - api

        mongo:
                image: mongo:latest
                volumes:
                        - type: volume
                          source: mongo
                          target: /data/db

        api:
                image: hmsbennett/pool_api:latest
                depends_on:
                        - mongo

        jenkins:
                image: hmsbennett/jenkins:latest
                volumes:
                        - type: volume
                          source: ./jenkins-home
                          target: /var/jenkins_home
                        - type: bind
                          source: /var/run/docker.sock
                          target: /var/run/docker.sock
                environment:
                        - JENKINS_OPTS="--prefix=/jenkins"
