version: "3.7"

volumes:
        mongo:

services:
        api:
                image: api:latest
                container_name: backend
                build: ./api
                depends_on:
                        - mongo

        mongo:
                image: mongo:latest
                container_name: database
                volumes:
                        - type: volume
                          source: mongo
                          target: /data

        nginx:
                image: nginx:latest
                container_name: frontend
                volumes:
                        - type: bind
                          source: ./nginx.conf
                          target: /etc/nginx/nginx.conf
                ports:
                        - target: 80
                          published: 80
                         
