version: "3.7"

volumes:
        jenkins-home:

        mongo:

services:
        ui:
                image: ui:latesti
                container_name: frontend
                build: ./ui
                ports:
                        - target: 80
                          published: 80
                depends_on:
                        - jenkins
                        - api

        api:
                image: api:latest
                container_name: backend
                build: ./api
                depends_on:
                        - mongo

        mongo:
                image: mongo:latest
                container_name: database
                volumes:
                        - type: volume
                          source: mongo
                          target: /data/db

        jenkins:
                image: jenkins:bobcrutchley/jenkins:latest
                container_name: jenkins
                volumes:
                        - type: volume
                          source: ./jenkins-home
                          target: /var/jenkins_home
                        - type: bind
                          source: /var/run/docker.sock
                          target: /var/run/docker.sock

