version: "3.7"

volumes:
        jenkins-home:

services:

        jenkins:
                image: hmsbennett/jenkins:latest
                volumes:
                        - type: volume
                          source: ./jenkins-home
                          target: /var/jenkins_home
                        - type: bind
                          source: /var/run/docker.sock
                          target: /var/run/docker.sock
                environment:
                        - JENKINS_OPTS="--prefix=/jenkins"
